# Generated by Django 4.1.6 on 2023-02-07 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundtrip', models.BooleanField(default=True)),
                ('oneway', models.BooleanField(default=False)),
                ('multi_station', models.BooleanField(default=False)),
                ('departing', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_date', models.DateTimeField(default=datetime.datetime.now)),
                ('return_date', models.DateTimeField(blank=True)),
                ('adults', models.IntegerField(default=1)),
                ('children', models.IntegerField(default=0)),
            ],
        ),
    ]
